### ISSUE TITLE
Can't get system path to find SQLShare client.

### ISSUE THREAD

**Issue by kubu4** [uwescience/sqlshare-pythonclient#21]
When I try to run any of the SQLShare client commands outside of the ```sqlshare-pythonclient/tools``` directory, I get the following error:

```python: can't open file 'fetchdata.py': [Errno 2] No such file or directory```

SQLShare works fine when I'm in the ```sqlshare-pythonclient/tools```, but it would be much more convenient if I could run SQLShare from any directory instead of having to change to the ```sqlshare-pythonclient/tools``` directory to execute the various commands.  

If someone could glance at my system info and let me know what I'm doing wrong, I'd greatly appreciate it.  I don't even know where to start to try to get this set up properly. Thanks for your help!

System Info:

Ubuntu 14.04 LTS

Here's my Python system path:
```
>>> import sys
>>> sys.path
['', '/usr/local/lib/python2.7/dist-packages/SQLShare-0.1a-py2.7.egg', 
'/usr/local/lib/python2.7/dist-packages/distribute-0.6.49-py2.7.egg', 
'/usr/local/lib/python2.7/dist-packages/bcbio_gff-0.5a-py2.7.egg', 
'/home/samb', 
'/home/samb/sqlshare-pythonclient/sqlshare', 
'/home/samb/BioinformaticsTools/sqlshare-pythonclient/tools', 
'/usr/lib/python2.7', 
'/usr/lib/python2.7/plat-x86_64-linux-gnu', 
'/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', 
'/usr/lib/python2.7/lib-dynload', 
'/usr/local/lib/python2.7/dist-packages', 
'/usr/lib/python2.7/dist-packages', 
'/usr/lib/python2.7/dist-packages/PILcompat', 
'/usr/lib/python2.7/dist-packages/gtk-2.0', 
'/usr/lib/pymodules/python2.7', 
'/usr/lib/python2.7/dist-packages/ubuntu-sso-client']
```
Here's the end of my .bashrc file:
```
# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi
export PYTHONPATH=$PYTHONPATH:/home/samb/BioinformaticsTools/sqlshare-pythonclient/tools
export PATH=/usr/lib/jdk/bin:$PATH
export CLASSPATH=.
```

**Comment by dhalperi** [comment]
What actual command are you running?

**Comment by kubu4** [comment]
$```python fetchdata.py -d "[samwhite@washington.edu].[SumsCGs]" -f tsv -o sumcsgs.txt```

**Comment by billhowe** [comment]
Try this:

Copy the tools you wish to use elsewhere to /usr/local/bin and make sure they are executable:
$ cp tools/fetchdata.py /usr/local/bin/
$ chmod +x /usr/local/bin/fetchdata.py

Then you can run them from anywhere, but call them directly rather than invoking python:
$ fetchdata.py -d "[samwhite@washington.edu].[SumsCGs]" -f tsv -o sumcsgs.txt

**Comment by kubu4** [comment]
Beauty, that works! 

Thanks @dhalperi and @billhowe!

Any thoughts on why that was necessary?

**Comment by dhalperi** [comment]
When you say `python file.py`, this means "run the program `python` with the arguments `file.py`".

Your shell will search paths to find the program it is to run, e.g., `python`. But Python, in turn, interprets the `file.py` as the fully-defined path to the Python file to run – Python does not search any paths here.

Bill had you do two things:

1. make the `fetchdata.py` file executable (`chmod +x`), so that it counts as a "program" on Linux -- you need to be able to execute a program.
2. put the `fetchdata.py` program somewhere in your `PATH` so that your shell will find it.

**Comment by kubu4** [comment]
Thanks for the explanation.

**Comment by kubu4** [comment]
I'm just going to add this to the conversation for posterity sake.

Instead of copying all the tools to ```/usr/local/bin/```, I changed my ```.bashrc``` and then added executable permissions to all the SQLShare tools.

Previously ```.bashrc``` contained the following line:

```export PYTHONPATH=$PYTHONPATH:/home/samb/BioinformaticsTools/sqlshare-pythonclient/tools```

Changed that line to the following (has PATH instead of PYTHONPATH):
```export PATH=$PATH:/home/samb/BioinformaticsTools/sqlshare-pythonclient/tools```

**Comment by billhowe** [comment]
That works too, and is a much cleaner solution!
